### PR TITLE
pinning right_api_client to 1.6.2

### PR DESCRIPTION
**Pull request by rshade**

### CODE REVIEW

**Comment by rshade** [comment]
```
      Recipe: machine_tag::default
         * chef_gem[machine_tag] action install
           - install version 1.1.3 of package machine_tag
         * chef_gem[right_api_client] action install
           - install version 1.6.2 of package right_api_client
         Converging 4 resources
         * log[Installing 'machine_tag' gem] action write

       Recipe: build-essential::default
         * build_essential[install_packages] action install
           * yum_package[autoconf, bison, flex, gcc, gcc-c++, gettext, kernel-devel, make, m4, ncurses-devel, patch] action install (up to date)
            (up to date)
       Recipe: machine_tag::default
         * chef_gem[machine_tag] action install (up to date)
         * chef_gem[right_api_client] action install (up to date)

       Running handlers:
       Running handlers complete
       Chef Client finished, 5/9 resources updated in 01 minutes 46 seconds
       Finished converging <default-centos-68> (2m50.85s).
-----> Kitchen is finished. (5m30.02s)```

**Comment by SirJko** [comment]
Hi

I am giving a try with this new Chef 12 migration and when installing MySQL, at some point uses this recipe:

https://github.com/rightscale-cookbooks/machine_tag/blob/master/recipes/default.rb

I think it is failing here as I am receiving this error:

ERROR: machine_tag[server:uuid=04-XXXX....] (rightscale_tag::default line 28) had an error: Gem::ConflictError: Unable to activate right_api_client-1.6.2, because json-2.0.2 conflicts with json (~> 1.0)

Anyone has any insight on how to fix this?

**Comment by rshade** [comment]
@SirJko you need chef12.17 or below. I will be releasing a later one that supports 12.18 and above only

**Comment by SirJko** [comment]
This made the trick for this issue. Many thanks!

**Pull request merged**
